// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jailtonjunior94/go-uow/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CourseRepositoryInterface is an autogenerated mock type for the CourseRepositoryInterface type
type CourseRepositoryInterface struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, course
func (_m *CourseRepositoryInterface) Insert(ctx context.Context, course entity.Course) error {
	ret := _m.Called(ctx, course)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCourseRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCourseRepositoryInterface creates a new instance of CourseRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCourseRepositoryInterface(t mockConstructorTestingTNewCourseRepositoryInterface) *CourseRepositoryInterface {
	mock := &CourseRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
