// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import ()

type Category struct {
	ID          string
	Name        string
	Description string
}

type Course struct {
	ID          string
	CategoryID  string
	Name        string
	Description string
}
